### PR TITLE
Update WelcomeMessages.cs

### PR DESCRIPTION
**Pull request by adv0catus**
Add aliases for `>setwelcomemessage` and `>setleavemessage` temporarily until commands/functionality can be reworked.

### CODE REVIEW

**Comment by LovingMelody** [comment]
Not a huge fan of these changes, alias should be intuitive and these are not.

**Comment by LovingMelody** [comment]
Over looked the suggestion in the discord channel, only did a quick look in issues.

**Comment by Drummss** [comment]
What was the suggestion?

**Comment by adv0catus** [comment]
Add aliases.

**Pull request closed without merging**
