### PR TITLE
Refactor RpsService

### PR DESCRIPTION
**Pull request by velddev**
- Removed parse from the model, as the model shouldn't have any business logic attached.
- Created `GetWeapon` to replace RpsWeapon.Parse or TryParse.
- Removed the list of weapons from RpsWeapon to integrate with only the service.
- Fixed Optional<T> for value types.

### CODE REVIEW

**Comment by velddev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 1
           

Complexity increasing per file
==============================
- test/Miki.Tests/Services/RpsServiceTests.cs  1
         

Complexity decreasing per file
==============================
+ src/Miki/Services/Rps/RpsService.cs  -1
+ src/Miki/Services/Rps/RpsWeapon.cs  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/velddev/Miki/pullRequest?prid=5130537&bid=16860241)

**Review by Drummss — APPROVED** [review]
This looks really good Veld! I realise this is code that you hadn't changed in your commit but if you're up for a bit of cleanup there's a couple of variables that can be changed to `var` on lines `70, 71, and 98`. The `VictoryStatus` enum members should also be pascal case.

**Comment by velddev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- test/Miki.Tests/Services/RpsServiceTests.cs  1
         

Complexity decreasing per file
==============================
+ src/Miki/Services/Rps/RpsWeapon.cs  -1
+ src/Miki/Services/Rps/RpsService.cs  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/velddev/Miki/pullRequest?prid=5130537&bid=16860241)

**Comment by velddev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- test/Miki.Tests/Services/RpsServiceTests.cs  1
         

Complexity decreasing per file
==============================
+ src/Miki/Services/Rps/RpsWeapon.cs  -1
+ src/Miki/Services/Rps/RpsService.cs  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/velddev/Miki/pullRequest?prid=5130537&bid=16860241)

**Review by Drummss — APPROVED** [review]
Nice and clean now, maybe put the `GameResult` enum outside of the `Miki.Service.Rps` scope so other games can use it? Overall looks pretty good now!

**Comment by velddev** [comment]
Sounds like a follow-up task for when we actually implement other games with this type.

**Pull request merged**
