### PR TITLE
Update FunModule.cs

### PR DESCRIPTION
**Pull request by adv0catus**
* Fixed spacing for roulette command code
* Reuploaded existing `>greentext` images as anonymous and added more images

### CODE REVIEW

**Comment by LovingMelody** [comment]
This doesn't really fix anything and just makes it harder to track change history.
Edit: didn't read full changes.

**Comment by LovingMelody** [comment]
Reviewing images.

**Comment by LovingMelody** [comment]
Several of these images violate discord TOS. Declined

**Comment by adv0catus** [comment]
can you be more specific.

**Comment by adv0catus** [comment]
also, you realize those images are already live, just switching to an anonymous upload, right

**Pull request closed without merging**
